### ISSUE TITLE
"sslcafile" or "sslcapath" option are properly set for the environment.

### ISSUE THREAD

**Issue by webdesign7** [szmnmichalowski/ZF2-NoCaptcha#1]
Hello ! 
Using your module in my project but every-time I submit the form it throws the below error:
Any ideas what that could be ? 

Thanks
Sergiu C.

File:

```
/home/dir/core/vendor/zendframework/zendframework/library/Zend/Http/Client/Adapter/Socket.php:308
```

Message:

```
Unable to enable crypto on TCP connection www.google.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.
```

Stack trace:

```
#0 /home/dir/core/vendor/zendframework/zendframework/library/Zend/Http/Client.php(1362): Zend\Http\Client\Adapter\Socket->connect('www.google.com', 443, true)
#1 /home/dir/core/vendor/zendframework/zendframework/library/Zend/Http/Client.php(890): Zend\Http\Client->doRequest(Object(Zend\Uri\Http), 'GET', true, Array, '')
#2 /home/dir/core/vendor/szmnmichalowski/zf2-nocaptcha/src/NoCaptcha/Service/ReCaptcha.php(103): Zend\Http\Client->send()
```

**Comment by catilgan** [comment]
Hi Sergiu,

I had the same issue, until i found the right answer in a ZF2 forum. Try to configure your captcha element with following options:

``` php
        $options = [
            'secret_key' => 'xxxxxx',
            'site_key' => 'xxxxx',
            'sslverifypeer' => false,
            'type' => 'image',
            'theme' => 'light',
        ];

        $recaptcha = new \NoCaptcha\Captcha\ReCaptcha($options);

        $recaptcha->getService()->setOption('adapter', 'Zend\Http\Client\Adapter\Curl');

        $captchaElement = new \Zend\Form\Element\Captcha();
        $captchaElement->setCaptcha($recaptcha);
```

You have to set the _sslverifypeer_ value to _false_ and use the _Zend\Http\Client\Adapter\Curl_ class as the request adapter.

See this forum entry for detailed information (http://zend-framework-community.634137.n4.nabble.com/SSL-issue-td4660987.html)
